/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DisabledIndexRouteImport } from './routes/_disabled/index'
import { Route as EntriesChar123EntryIdChar125RouteImport } from './routes/entries.{-$entryId}'
import { Route as DisabledServerRouteImport } from './routes/_disabled/server'
import { Route as DisabledClientOnlyRouteImport } from './routes/_disabled/client-only'
import { Route as DisabledClientOnlyIndexRouteImport } from './routes/_disabled/client-only.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DisabledIndexRoute = DisabledIndexRouteImport.update({
  id: '/_disabled/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesChar123EntryIdChar125Route =
  EntriesChar123EntryIdChar125RouteImport.update({
    id: '/entries/{-$entryId}',
    path: '/entries/{-$entryId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const DisabledServerRoute = DisabledServerRouteImport.update({
  id: '/_disabled/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const DisabledClientOnlyRoute = DisabledClientOnlyRouteImport.update({
  id: '/_disabled/client-only',
  path: '/client-only',
  getParentRoute: () => rootRouteImport,
} as any)
const DisabledClientOnlyIndexRoute = DisabledClientOnlyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DisabledClientOnlyRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/client-only': typeof DisabledClientOnlyRouteWithChildren
  '/server': typeof DisabledServerRoute
  '/entries/{-$entryId}': typeof EntriesChar123EntryIdChar125Route
  '/': typeof DisabledIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/client-only/': typeof DisabledClientOnlyIndexRoute
}
export interface FileRoutesByTo {
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/server': typeof DisabledServerRoute
  '/entries/{-$entryId}': typeof EntriesChar123EntryIdChar125Route
  '/': typeof DisabledIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/client-only': typeof DisabledClientOnlyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_disabled/client-only': typeof DisabledClientOnlyRouteWithChildren
  '/_disabled/server': typeof DisabledServerRoute
  '/entries/{-$entryId}': typeof EntriesChar123EntryIdChar125Route
  '/_disabled/': typeof DisabledIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_disabled/client-only/': typeof DisabledClientOnlyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/client-only'
    | '/server'
    | '/entries/{-$entryId}'
    | '/'
    | '/api/auth/$'
    | '/client-only/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/server'
    | '/entries/{-$entryId}'
    | '/'
    | '/api/auth/$'
    | '/client-only'
  id:
    | '__root__'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_disabled/client-only'
    | '/_disabled/server'
    | '/entries/{-$entryId}'
    | '/_disabled/'
    | '/api/auth/$'
    | '/_disabled/client-only/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DisabledClientOnlyRoute: typeof DisabledClientOnlyRouteWithChildren
  DisabledServerRoute: typeof DisabledServerRoute
  EntriesChar123EntryIdChar125Route: typeof EntriesChar123EntryIdChar125Route
  DisabledIndexRoute: typeof DisabledIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_disabled/': {
      id: '/_disabled/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DisabledIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/{-$entryId}': {
      id: '/entries/{-$entryId}'
      path: '/entries/{-$entryId}'
      fullPath: '/entries/{-$entryId}'
      preLoaderRoute: typeof EntriesChar123EntryIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_disabled/server': {
      id: '/_disabled/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof DisabledServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_disabled/client-only': {
      id: '/_disabled/client-only'
      path: '/client-only'
      fullPath: '/client-only'
      preLoaderRoute: typeof DisabledClientOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_disabled/client-only/': {
      id: '/_disabled/client-only/'
      path: '/'
      fullPath: '/client-only/'
      preLoaderRoute: typeof DisabledClientOnlyIndexRouteImport
      parentRoute: typeof DisabledClientOnlyRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DisabledClientOnlyRouteChildren {
  DisabledClientOnlyIndexRoute: typeof DisabledClientOnlyIndexRoute
}

const DisabledClientOnlyRouteChildren: DisabledClientOnlyRouteChildren = {
  DisabledClientOnlyIndexRoute: DisabledClientOnlyIndexRoute,
}

const DisabledClientOnlyRouteWithChildren =
  DisabledClientOnlyRoute._addFileChildren(DisabledClientOnlyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DisabledClientOnlyRoute: DisabledClientOnlyRouteWithChildren,
  DisabledServerRoute: DisabledServerRoute,
  EntriesChar123EntryIdChar125Route: EntriesChar123EntryIdChar125Route,
  DisabledIndexRoute: DisabledIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
